### ISSUE TITLE
Patch 2.3.1 should be a major version bump (3.x)

### ISSUE THREAD

**Issue by theycallmeswift** [peopledatalabs/peopledatalabs-ruby#19]
**Describe the bug**
A recent patch was released labeled 2.3.1. As a patch level update, it should only include backward compatible bug fixes. However, this change includes an API change that breaks backward compatibility.

**To Reproduce**

```
     Failure/Error:
       response = Peopledatalabs::Autocomplete.retrieve(
         field: type,
         text: name,
         pretty: true,
         titlecase: true,
         beta: true
       ).deep_symbolize_keys

     ArgumentError:
       Invalid keyword arguments provided: beta
```

**Expected behavior**
Either:
1. Maintain backward compatibility and print a warning if a deprecated param is used
2. Update the major version of the library

**Additional context**
This is the commit that broke things: https://github.com/peopledatalabs/peopledatalabs-ruby/commit/0b461f2e713c18111397626ffea52551d5013ec9

**Comment by theycallmeswift** [comment]
Tagging @vvillait88 since you merged the commit. LMK if I can provide additional context

**Comment by vvillait88** [comment]
@theycallmeswift thanks for flagging, we yanked the latest version and will update to a major version

**Comment by theycallmeswift** [comment]
@vvillait88 excellent, thanks! Just to confirm, there is no expected change to the API response object with `beta` removed going forward?

**Comment by vvillait88** [comment]
@theycallmeswift that is correct, we changed the underlying infrastructure powering our autocomplete and now have moved all call to that.  We added new functionality where we allow lookups by website now but you can read more about that on our docs: https://docs.peopledatalabs.com/docs/autocomplete-api.
